#!/usr/bin/env bash
# Inspired and partially copied by https://github.com/gf3/dotfiles

VALID_PARAMS="nsu"

system_type=$(uname -s)

RCol='\e[0m'    # Text Reset

# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
Bla='\e[0;30m';     BBla='\e[1;30m';    UBla='\e[4;30m';    IBla='\e[0;90m';    BIBla='\e[1;90m';   On_Bla='\e[40m';    On_IBla='\e[0;100m';
Red='\e[0;31m';     BRed='\e[1;31m';    URed='\e[4;31m';    IRed='\e[0;91m';    BIRed='\e[1;91m';   On_Red='\e[41m';    On_IRed='\e[0;101m';
Gre='\e[0;32m';     BGre='\e[1;32m';    UGre='\e[4;32m';    IGre='\e[0;92m';    BIGre='\e[1;92m';   On_Gre='\e[42m';    On_IGre='\e[0;102m';
Yel='\e[0;33m';     BYel='\e[1;33m';    UYel='\e[4;33m';    IYel='\e[0;93m';    BIYel='\e[1;93m';   On_Yel='\e[43m';    On_IYel='\e[0;103m';
Blu='\e[0;34m';     BBlu='\e[1;34m';    UBlu='\e[4;34m';    IBlu='\e[0;94m';    BIBlu='\e[1;94m';   On_Blu='\e[44m';    On_IBlu='\e[0;104m';
Pur='\e[0;35m';     BPur='\e[1;35m';    UPur='\e[4;35m';    IPur='\e[0;95m';    BIPur='\e[1;95m';   On_Pur='\e[45m';    On_IPur='\e[0;105m';
Cya='\e[0;36m';     BCya='\e[1;36m';    UCya='\e[4;36m';    ICya='\e[0;96m';    BICya='\e[1;96m';   On_Cya='\e[46m';    On_ICya='\e[0;106m';
Whi='\e[0;37m';     BWhi='\e[1;37m';    UWhi='\e[4;37m';    IWhi='\e[0;97m';    BIWhi='\e[1;97m';   On_Whi='\e[47m';    On_IWhi='\e[0;107m';

banner=$(cat <<- "END"
 __        __   _                             _  _   _  ___  __  __ _____
 \ \      / /__| | ___ ___  _ __ ___   ___   | || | | |/ _ \|  \/  | ____|
  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ / __) |_| | | | | |\/| |  _|
   \ V  V /  __/ | (_| (_) | | | | | |  __/ \__ \  _  | |_| | |  | | |___
    \_/\_/ \___|_|\___\___/|_| |_| |_|\___| (   /_| |_|\___/|_|  |_|_____|
                                             |_|
END
)

# ────────────────
# Helper functions
# ────────────────

title() {
  echo -e "${BBlu}❯ ${BGre}$*${RCol}"
}

warn() {
  echo -e "${BRed}$*${RCol}" >&2
}

get_packages() {
  sed -e 's/#.*//' -e '/^[[:space:]]*$/d' -e 's/[[:space:]]\+//g' "$1" | tr '\n' ' '
}

do_execute() {
  local dryRun
  local opt
  local OPTIND
  local sh
  local useSudo

  dryRun=0
  useSudo=0

  while getopts ${VALID_PARAMS} opt; do
    case ${opt} in
      n)
        dryRun=1
        ;;
      s)
        useSudo=1
        ;;
      ?)
        ;;
    esac
  done
  shift $((OPTIND-1))

  sh=$@

  [ $useSudo -eq 1 ] && sh="sudo $sh"

  printf "  "

  [ $dryRun -eq 1 ] && printf "${Red}(dry run)${RCol} "

  echo -e "${BBlu}\$${BWhi} $sh ${RCol}"

  [ $dryRun -eq 0 ] && sh -c "$sh"
}

# ───────────────
# Setup functions
# ───────────────

setup_ubuntu() {
  local opt
  local OPTIND
  local ui=0
  local apt_base_path="$HOME/.config/yadm/install/apt"
  local pip_packages="$HOME/.config/yadm/install/pip/packages"
  local install_scripts="$HOME/.config/yadm/install/script"
  
  while getopts ${VALID_PARAMS} opt; do
    case ${opt} in
      u)
        ui=1
        ;;
      ?)
        ;;
    esac
  done

  title "Update package manager"
  do_execute "$@" -s "apt update"
  do_execute "$@" -s "apt -y upgrade"

  title "Install required packages"
  do_execute "$@" -s "apt -y install apt-transport-https curl dpkg-dev git jq"

  setup_apt "${apt_base_path}/headless" "$@"
  [ $ui -eq 1 ] && setup_apt "${apt_base_path}/ui" "$@"

  setup_via_script "${install_scripts}/headless" "$@"
  [ $ui -eq 1 ] && setup_via_script "${install_scripts}/ui" "$@"

  setup_pip "${pip_packages}" "$@"

  title "Set shell to zsh"
  if cmd-exists zsh; then
    do_execute "$@" "chsh -s $(which zsh)"
  else
    warn "Cannot find zsh"
  fi
}

setup_apt() {
  local apt_packages="$1"/packages
  local apt_prep="$1"/prepare
  shift
  
  title "Prepare package installation"
  if [ -d "$apt_prep" ]; then
    for prep in "$apt_prep"/*; do
      do_execute "$@" "$prep"
    done
  fi

  title "Installing packages from ${apt_packages#"$HOME"/.config/yadm/}"
  if [ -f "$apt_packages" ]; then
    do_execute "$@" -s "apt update"
    do_execute "$@" -s "apt -y install $(get_packages $apt_packages)"
  fi
}

setup_via_script() {
  local script_path="$1"
  shift

  title "Run install scripts from ${script_path#"$HOME"/.config/yadm/}"
  if [ -d "$script_path" ]; then
    for install_script in "$script_path"/*; do
      do_execute "$@" "$install_script"
    done
  fi
}

setup_pip() {
  local pip_packages="$1"
  shift

  title "Install pip packages from ${pip_packages#"$HOME"/.config/yadm/}"
  if [ -f "$pip_packages" ]; then
    do_execute "$@" "pip3 install --user $(get_packages $pip_packages)"
  fi
}

setup_macos() {
  local pip_packages="$HOME/.config/yadm/install/pip/packages"

  if ! cmd-exists brew; then
    title "Install Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  title "Install brew packages"
  brew bundle install

  setup_pip "${pip_packages}" "$@"
}

# ────────────
# Bootstrapper
# ────────────

echo -e "${BGre}${banner}${RCol}\n"

if [[ ! -w ~/.config/git/config.user ]]; then
  cat << 'END_GIT_USER' > ~/.config/git/config.user
[user]
  name = 
  email = 
END_GIT_USER
  $VISUAL ~/.config/git/config.user
  title "Git user set to '$(git whoami)'"
else
  title "Git user is already set to '$(git whoami)'"
fi

if [ "$system_type" = "Linux" ]; then
  release_name=$(lsb_release -si)
  if [ "$release_name" = "Ubuntu" ]; then
    title "System: $system_type $release_name"
    setup_ubuntu "$@"
  else
    warn "No support for ${release_name}"
  fi
elif [ "$system_type" = "Darwin" ]; then
  title "System: $system_type"
  setup_macos "$@"
else
  warn "No support for $system_type"
fi

