#!/bin/bash
# Inspired and partially copied by https://github.com/gf3/dotfiles

system_type=$(uname -s)

RCol='\e[0m'    # Text Reset

# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
Bla='\e[0;30m';     BBla='\e[1;30m';    UBla='\e[4;30m';    IBla='\e[0;90m';    BIBla='\e[1;90m';   On_Bla='\e[40m';    On_IBla='\e[0;100m';
Red='\e[0;31m';     BRed='\e[1;31m';    URed='\e[4;31m';    IRed='\e[0;91m';    BIRed='\e[1;91m';   On_Red='\e[41m';    On_IRed='\e[0;101m';
Gre='\e[0;32m';     BGre='\e[1;32m';    UGre='\e[4;32m';    IGre='\e[0;92m';    BIGre='\e[1;92m';   On_Gre='\e[42m';    On_IGre='\e[0;102m';
Yel='\e[0;33m';     BYel='\e[1;33m';    UYel='\e[4;33m';    IYel='\e[0;93m';    BIYel='\e[1;93m';   On_Yel='\e[43m';    On_IYel='\e[0;103m';
Blu='\e[0;34m';     BBlu='\e[1;34m';    UBlu='\e[4;34m';    IBlu='\e[0;94m';    BIBlu='\e[1;94m';   On_Blu='\e[44m';    On_IBlu='\e[0;104m';
Pur='\e[0;35m';     BPur='\e[1;35m';    UPur='\e[4;35m';    IPur='\e[0;95m';    BIPur='\e[1;95m';   On_Pur='\e[45m';    On_IPur='\e[0;105m';
Cya='\e[0;36m';     BCya='\e[1;36m';    UCya='\e[4;36m';    ICya='\e[0;96m';    BICya='\e[1;96m';   On_Cya='\e[46m';    On_ICya='\e[0;106m';
Whi='\e[0;37m';     BWhi='\e[1;37m';    UWhi='\e[4;37m';    IWhi='\e[0;97m';    BIWhi='\e[1;97m';   On_Whi='\e[47m';    On_IWhi='\e[0;107m';

banner=$(cat <<- "END"
 __        __   _                             _  _   _  ___  __  __ _____
 \ \      / /__| | ___ ___  _ __ ___   ___   | || | | |/ _ \|  \/  | ____|
  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ / __) |_| | | | | |\/| |  _|
   \ V  V /  __/ | (_| (_) | | | | | |  __/ \__ \  _  | |_| | |  | | |___
    \_/\_/ \___|_|\___\___/|_| |_| |_|\___| (   /_| |_|\___/|_|  |_|_____|
                                             |_|
END
)

# ────────────────
# Helper functions
# ────────────────

title() {
  echo -e "${BBlu}❯ ${Gre}${@}${RCol}"
}

warn() {
  echo "${Red}$@${RCol}" >&2
}

do_execute() {
  local dryRun
  local opt
  local OPTARG
  local OPTIND
  local sh
  local useSudo

  dryRun=0
  useSudo=0

  while getopts "ns" opt; do
    case ${opt} in
      n)
        dryRun=1
        ;;
      s)
        useSudo=1
        ;;
      \?)
        echo "Invalid option: -$OPTARG" >&2
        ;;
    esac
  done
  shift $((OPTIND-1))

  sh=$@

  [ $useSudo -eq 1 ] && sh="/usr/bin/sudo $sh"

  printf "  "

  [ $dryRun -eq 1 ] && printf "${Red}(dry run)${RCol} "

  echo -e "\$ $sh"

  [ $dryRun -eq 0 ] && sh -c "$sh"
}

# ────────────
# Bootstrapper
# ────────────

echo -e "${BGre}${banner}${RCol}\n\n"

if [ "$system_type" = "Linux" ]; then
  release_name=$(lsb_release -si)
  if [ "$release_name" = "Ubuntu" ]; then
    title "$system_type $release_name"
    title "Installing packages from $HOME/.config/yadm/install/apt/server/install"
    if [ -f "$HOME/.config/yadm/install/apt/server/install" ]; then
      do_execute $@ -s "apt -y install $(tr '\n' ' ' < $HOME/.config/yadm/install/apt/server/install)"
    else
      warn "Missing `$HOME/.config/yadm/install/apt/server/install` package list"
    fi
  else
    warn "No support for ${release_name}"
  fi
elif [ "$system_type" = "Darwin" ]; then
  warn "MacOs is not yet supported"
fi

