#!/bin/bash
# Inspired and partially copied by https://github.com/gf3/dotfiles

VALID_PARAMS="nsu"

system_type=$(uname -s)

RCol='\e[0m'    # Text Reset

# Regular           Bold                Underline           High Intensity      BoldHigh Intens     Background          High Intensity Backgrounds
Bla='\e[0;30m';     BBla='\e[1;30m';    UBla='\e[4;30m';    IBla='\e[0;90m';    BIBla='\e[1;90m';   On_Bla='\e[40m';    On_IBla='\e[0;100m';
Red='\e[0;31m';     BRed='\e[1;31m';    URed='\e[4;31m';    IRed='\e[0;91m';    BIRed='\e[1;91m';   On_Red='\e[41m';    On_IRed='\e[0;101m';
Gre='\e[0;32m';     BGre='\e[1;32m';    UGre='\e[4;32m';    IGre='\e[0;92m';    BIGre='\e[1;92m';   On_Gre='\e[42m';    On_IGre='\e[0;102m';
Yel='\e[0;33m';     BYel='\e[1;33m';    UYel='\e[4;33m';    IYel='\e[0;93m';    BIYel='\e[1;93m';   On_Yel='\e[43m';    On_IYel='\e[0;103m';
Blu='\e[0;34m';     BBlu='\e[1;34m';    UBlu='\e[4;34m';    IBlu='\e[0;94m';    BIBlu='\e[1;94m';   On_Blu='\e[44m';    On_IBlu='\e[0;104m';
Pur='\e[0;35m';     BPur='\e[1;35m';    UPur='\e[4;35m';    IPur='\e[0;95m';    BIPur='\e[1;95m';   On_Pur='\e[45m';    On_IPur='\e[0;105m';
Cya='\e[0;36m';     BCya='\e[1;36m';    UCya='\e[4;36m';    ICya='\e[0;96m';    BICya='\e[1;96m';   On_Cya='\e[46m';    On_ICya='\e[0;106m';
Whi='\e[0;37m';     BWhi='\e[1;37m';    UWhi='\e[4;37m';    IWhi='\e[0;97m';    BIWhi='\e[1;97m';   On_Whi='\e[47m';    On_IWhi='\e[0;107m';

banner=$(cat <<- "END"
 __        __   _                             _  _   _  ___  __  __ _____
 \ \      / /__| | ___ ___  _ __ ___   ___   | || | | |/ _ \|  \/  | ____|
  \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ / __) |_| | | | | |\/| |  _|
   \ V  V /  __/ | (_| (_) | | | | | |  __/ \__ \  _  | |_| | |  | | |___
    \_/\_/ \___|_|\___\___/|_| |_| |_|\___| (   /_| |_|\___/|_|  |_|_____|
                                             |_|
END
)

# ────────────────
# Helper functions
# ────────────────

title() {
  echo -e "${BBlu}❯ ${Gre}${@}${RCol}"
}

warn() {
  echo -e "${Red}$@${RCol}" >&2
}

do_execute() {
  local dryRun
  local opt
  local OPTIND
  local sh
  local useSudo

  dryRun=0
  useSudo=0

  while getopts ${VALID_PARAMS} opt; do
    case ${opt} in
      n)
        dryRun=1
        ;;
      s)
        useSudo=1
        ;;
      ?)
        ;;
    esac
  done
  shift $((OPTIND-1))

  sh=$@

  [ $useSudo -eq 1 ] && sh="sudo $sh"

  printf "  "

  [ $dryRun -eq 1 ] && printf "${Red}(dry run)${RCol} "

  echo -e "${Blu}\$${RCol} $sh"

  [ $dryRun -eq 0 ] && sh -c "$sh"
}

# ───────────────
# Setup functions
# ───────────────

setup_linux() {
  local opt
  local OPTIND
  local ui=0
  local apt_base_path="$HOME/.config/yadm/install/apt"
  
  while getopts ${VALID_PARAMS} opt; do
    case ${opt} in
      u)
        ui=1
        ;;
      ?)
        ;;
    esac
  done

  title "Update package manager"
  do_execute $@ -s "apt update"
  do_execute $@ -s "apt -y upgrade"

  title "Install required packages"
  do_execute $@ -s "apt -y install apt-transport-https curl"

  setup_linux_impl "${apt_base_path}/server" $@
  [ $ui -eq 1 ] && setup_linux_impl "${apt_base_path}/ui" $@
}

setup_linux_impl() {
  local apt_packages="$1"/packages
  local apt_prep="$1"/prepare
  shift
  
  title "Prepare package installation and run custom install scripts"
  if [ -d "$apt_prep" ]; then
    for prep in $(find $apt_prep -type f); do
      do_execute $@ $prep
    done
  fi

  title "Installing packages from $apt_packages"
  if [ -f "$apt_packages" ]; then
    do_execute $@ -s "apt update"
    do_execute $@ -s "apt -y install $(tr '\n' ' ' < $apt_packages)"
  else
    warn "Missing `$apt_packages` package list"
  fi
}

# ────────────
# Bootstrapper
# ────────────

echo -e "${BGre}${banner}${RCol}\n"

if [ "$system_type" = "Linux" ]; then
  release_name=$(lsb_release -si)
  if [ "$release_name" = "Ubuntu" ]; then
    title "System: $system_type $release_name"
    setup_linux $@
  else
    warn "No support for ${release_name}"
  fi
else
  warn "No support for $system_type"
fi

