#!/usr/bin/env bash
#
# Run all installers

check-sudo() {
  # check if user has sudo rights
  if sudo -v; then
    export IS_SUDO=true
  else
    export IS_SUDO=false
  fi
}

install-ask() {
  if YES-no "Do you want to install $1?"; then 
    rml
    rml
	  install $1
  else
    rml
  fi
}

install() {
  info "Installing $1"
	#sh -c "${$1/install.sh}"
}

source ./script/helper/helper.sh

validate-dotfiles-env-var
cd "$DOTFILES"

source ./script/helper/logging.sh
source ./shell/profile.symlink

check-sudo

# run apt updates if possible
if [ IS_SUDO=true ]; then
  info 'Run apt update'
  #sudo apt update &>/dev/null
fi

# find the installers and run them iteratively
find . -maxdepth 2 -name install.sh > /tmp/to_install.txt
while read -u 3 installer ; do
  NAME="$(basename $(dirname ${installer}))"
  # todo: handle case where everything is installed without asking
  install-ask $NAME
done 3< /tmp/to_install.txt
