#!/usr/bin/env bash
#
# Run all setup scripts

setup-ask() {
  NAME="$(basename $(dirname $1))"
  if YES-no "Do you want to setup $NAME?"; then 
    rml
    rml
	  setup $1 $NAME
    return $?
  else
    rml
  fi
}

setup() {
  info "Setting up $2"
  sh -c "$1"
  return $?
}

source ./script/helper/helper.sh

validate-dotfiles-env-var
cd "$DOTFILES"

source ./script/helper/logging.sh
source ./shell/profile.symlink

# find the setup scripts and run them iteratively
find . -maxdepth 2 -name setup.sh > /tmp/to_setup.txt
while read -u 3 setter ; do
  # todo: handle case where everything is set up without asking
  setup-ask ${setter}
done 3< /tmp/to_setup.txt
